start-github-runner-ubuntu:
    stage: build
    image:
        name: hashicorp/vault:latest
        pull_policy: if-not-present
    before_script:
        - apk add --update curl && rm -rf /var/cache/apk/*
    script: |
        export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=gitlab-runner jwt=$CI_JOB_JWT)"
        export TAILSCALE_OAUTH_CLIENT_ID="$(vault kv get -field=client_id tailscale/oauth)"
        export TAILSCALE_OAUTH_CLIENT_SECRET="$(vault kv get -field=client_secret tailscale/oauth)"
        export TAILSCALE_TAGS='tag:ci'
        export GITHUB_TOKEN="$(vault kv get -field=token github/developer)"
        export GITLAB_REGISTRATION_TOKEN="$(vault kv get -field=token gitlab/runner-registration)"
        curl -H "Authorization: token ${GITHUB_TOKEN}" \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        "https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/gitlab-runner-ubuntu.yaml/dispatches" \
        -d '{"ref": "main", "inputs": {"registration_token": "'${GITLAB_REGISTRATION_TOKEN}'", "gitlab_url": "'${GITLAB_ADDR}'", "gitlab_runner_tag": "'githubrunner-ubuntu-${CI_PROJECT_ID}-${CI_PIPELINE_IID}'", "tailscale_oauth_client_id": "'${TAILSCALE_OAUTH_CLIENT_ID}'", "tailscale_oauth_client_secret": "'${TAILSCALE_OAUTH_CLIENT_SECRET}'", "tailscale_tags": "'${TAILSCALE_TAGS}'", "docker_image": "'docker:19.03.12'"}}'

build:
    stage: build
    image:
        name: ghcr.io/cicirello/pyaction:latest
        entrypoint: ['']
    before_script:
        - ARCH="$(dpkg --print-architecture)"
        - curl https://dl.min.io/client/mc/release/linux-${ARCH}/mc --create-dirs -o $HOME/.local/minio/bin/mc
        - chmod +x $HOME/.local/minio/bin/mc
        - export PATH=$PATH:$HOME/.local/minio/bin/
        - mc alias set oci $OCI_API_ENDPOINT $OCI_ACCESS_KEY $OCI_SECRET_KEY
        - apt-get -y update
        - apt-get install -y default-jdk bzip2 zip tar gzip
        - curl -s "https://get.sdkman.io" | bash
        - source "/root/.sdkman/bin/sdkman-init.sh"
        - sdk install gradle 8.6
    script:
        - ./gradlew clean build -x test
        - mc cp --recursive ./build/libs/*.jar oci/gitlab-ripmeapp/
    tags:
        - githubrunner-ubuntu-${CI_PROJECT_ID}-${CI_PIPELINE_IID}

deploy:
    stage: deploy
    image:
        name: ghcr.io/cicirello/pyaction:latest
        entrypoint: ['']
    dependencies:
        - build
    before_script:
        - ARCH="$(dpkg --print-architecture)"
        - curl https://dl.min.io/client/mc/release/linux-${ARCH}/mc --create-dirs -o $HOME/.local/minio/bin/mc
        - chmod +x $HOME/.local/minio/bin/mc
        - export PATH=$PATH:$HOME/.local/minio/bin/
        - mc alias set oci $OCI_API_ENDPOINT $OCI_ACCESS_KEY $OCI_SECRET_KEY
    script:
        - gh repo clone metril/ripmeapp metril_ripmeapp
        - cd ./metril_ripmeapp
        - mkdir compiled
        - mc cp --recursive oci/gitlab-ripmeapp/ ./compiled/
        - DATE=`TZ=":America/New_York" date +%Y-%m-%d_%H-%M`
        - TITLE=ripmeapp_${DATE}
        - gh release delete latest --yes
        - gh release create --latest --target master -t $TITLE latest ./compiled/*
    tags:
        - docker
        - amd64