build:jar:
    stage: build
    image: maven:latest
    script: mvn clean compile assembly:single
    artifacts:
        paths:
            - ./target/*.jar
        expire_in: 2 hours
    tags:
        - docker

deploy:jar:
    stage: deploy
    dependencies:
        - build:jar
    script:
        - cd ./target
        - jarfiles=$(find ./ -type f -name "*.jar"); mv $jarfiles[0] /cifs/atlas/gitlab_releases/RipMeApp/ripme.jar
    tags:
        - shell